//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuzzedroCMS.WebUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LuzzedroCMS.WebUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add bookmark.
        /// </summary>
        public static string AddBookmark {
            get {
                return ResourceManager.GetString("AddBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add category.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment.
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add image.
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding an image.
        /// </summary>
        public static string AddingAnImage {
            get {
                return ResourceManager.GetString("AddingAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding article.
        /// </summary>
        public static string AddingArticle {
            get {
                return ResourceManager.GetString("AddingArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tag.
        /// </summary>
        public static string AddTag {
            get {
                return ResourceManager.GetString("AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share with Google.
        /// </summary>
        public static string AddToGoogle {
            get {
                return ResourceManager.GetString("AddToGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string AddToTwitter {
            get {
                return ResourceManager.GetString("AddToTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article by category.
        /// </summary>
        public static string ArticleByCategory {
            get {
                return ResourceManager.GetString("ArticleByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article by tag.
        /// </summary>
        public static string ArticleByTag {
            get {
                return ResourceManager.GetString("ArticleByTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article was not found.
        /// </summary>
        public static string ArticleNotFound {
            get {
                return ResourceManager.GetString("ArticleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category doesn&apos;t contain any article.
        /// </summary>
        public static string ArticleNotFoundByCategory {
            get {
                return ResourceManager.GetString("ArticleNotFoundByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag doesn&apos;t contain any article.
        /// </summary>
        public static string ArticleNotFoundByTag {
            get {
                return ResourceManager.GetString("ArticleNotFoundByTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles - add.
        /// </summary>
        public static string ArticlesAdd {
            get {
                return ResourceManager.GetString("ArticlesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string Bookmarks {
            get {
                return ResourceManager.GetString("Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By sign in you agreed with.
        /// </summary>
        public static string BySignInYouAgreedWith {
            get {
                return ResourceManager.GetString("BySignInYouAgreedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot logout, please try again.
        /// </summary>
        public static string CannotLogout {
            get {
                return ResourceManager.GetString("CannotLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories - add.
        /// </summary>
        public static string CategoriesAdd {
            get {
                return ResourceManager.GetString("CategoriesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category&apos;s list.
        /// </summary>
        public static string CategoryList {
            get {
                return ResourceManager.GetString("CategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose image.
        /// </summary>
        public static string ChooseImage {
            get {
                return ResourceManager.GetString("ChooseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose tags.
        /// </summary>
        public static string ChooseTags {
            get {
                return ResourceManager.GetString("ChooseTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To finish it, click.
        /// </summary>
        public static string ClickToFinish {
            get {
                return ResourceManager.GetString("ClickToFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code of the e-mail has already expired. Try again to reset the password.
        /// </summary>
        public static string CodeExpired {
            get {
                return ResourceManager.GetString("CodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code messages do not exist in the system. Try again to reset the password.
        /// </summary>
        public static string CodeNotExists {
            get {
                return ResourceManager.GetString("CodeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        public static string CommentsToArticle {
            get {
                return ResourceManager.GetString("CommentsToArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string ConfigSite {
            get {
                return ResourceManager.GetString("ConfigSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation of registration on the site {0}.
        /// </summary>
        public static string ConfirmationRegistration {
            get {
                return ResourceManager.GetString("ConfirmationRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirming e-mail.
        /// </summary>
        public static string ConfirmingEmail {
            get {
                return ResourceManager.GetString("ConfirmingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correctly changed article.
        /// </summary>
        public static string CorrectlyChanged {
            get {
                return ResourceManager.GetString("CorrectlyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correctly edit comment.
        /// </summary>
        public static string CorrectlyEditComment {
            get {
                return ResourceManager.GetString("CorrectlyEditComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correctly set up the account. Welcome!.
        /// </summary>
        public static string CorrectlySetUp {
            get {
                return ResourceManager.GetString("CorrectlySetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current main photo.
        /// </summary>
        public static string CurrentMainPhoto {
            get {
                return ResourceManager.GetString("CurrentMainPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date added.
        /// </summary>
        public static string DateAdded {
            get {
                return ResourceManager.GetString("DateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? Please sign in via Facebook, Google or register setting an email.
        /// </summary>
        public static string DontHaveAccountRegister {
            get {
                return ResourceManager.GetString("DontHaveAccountRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit article.
        /// </summary>
        public static string EditArticle {
            get {
                return ResourceManager.GetString("EditArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category.
        /// </summary>
        public static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit comment.
        /// </summary>
        public static string EditComment {
            get {
                return ResourceManager.GetString("EditComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit data.
        /// </summary>
        public static string EditData {
            get {
                return ResourceManager.GetString("EditData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit tag.
        /// </summary>
        public static string EditTag {
            get {
                return ResourceManager.GetString("EditTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail, which will be sent instructions to reset your password.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail, which will be sent instructions to reset your password.
        /// </summary>
        public static string EnterEmailReset {
            get {
                return ResourceManager.GetString("EnterEmailReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail address that you use to login.
        /// </summary>
        public static string EnterLoginEmail {
            get {
                return ResourceManager.GetString("EnterLoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail, which will be used to log in.
        /// </summary>
        public static string EnterNewLoginEmail {
            get {
                return ResourceManager.GetString("EnterNewLoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a nickname that will be displayed near your content.
        /// </summary>
        public static string EnterNickname {
            get {
                return ResourceManager.GetString("EnterNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a sentence, which will be replaced with the name images.
        /// </summary>
        public static string EnterSequence {
            get {
                return ResourceManager.GetString("EnterSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again.
        /// </summary>
        public static string ErrorOcurred {
            get {
                return ResourceManager.GetString("ErrorOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to existing password.
        /// </summary>
        public static string ExistingPassword {
            get {
                return ResourceManager.GetString("ExistingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        public static string Favourites {
            get {
                return ResourceManager.GetString("Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must have a number of characters greater than {1}.
        /// </summary>
        public static string FieldMustHaveMoreChars {
            get {
                return ResourceManager.GetString("FieldMustHaveMoreChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must have a number of characters no larger than {1}.
        /// </summary>
        public static string FieldMustHaveNoMoreChars {
            get {
                return ResourceManager.GetString("FieldMustHaveNoMoreChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File cannot be more than 4MB.
        /// </summary>
        public static string FileCannotBeMore {
            get {
                return ResourceManager.GetString("FileCannotBeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not have any content.
        /// </summary>
        public static string FileNotHaveContent {
            get {
                return ResourceManager.GetString("FileNotHaveContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit photo.
        /// </summary>
        public static string FitPhoto {
            get {
                return ResourceManager.GetString("FitPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Article.
        /// </summary>
        public static string GoToArticle {
            get {
                return ResourceManager.GetString("GoToArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you received this message by mistake - ignore it.
        /// </summary>
        public static string IfReceivedMistake {
            get {
                return ResourceManager.GetString("IfReceivedMistake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images - add.
        /// </summary>
        public static string ImagesAdd {
            get {
                return ResourceManager.GetString("ImagesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        public static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect user name or password.
        /// </summary>
        public static string IncorectoUserNamePassword {
            get {
                return ResourceManager.GetString("IncorectoUserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file type.
        /// </summary>
        public static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invent a password.
        /// </summary>
        public static string InventPassword {
            get {
                return ResourceManager.GetString("InventPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of favourite articles.
        /// </summary>
        public static string ListFavArticles {
            get {
                return ResourceManager.GetString("ListFavArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of my comments.
        /// </summary>
        public static string ListMyComments {
            get {
                return ResourceManager.GetString("ListMyComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of articles.
        /// </summary>
        public static string ListOfArticles {
            get {
                return ResourceManager.GetString("ListOfArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of comments.
        /// </summary>
        public static string ListOfComments {
            get {
                return ResourceManager.GetString("ListOfComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Facebook.
        /// </summary>
        public static string LoginWithFacebook {
            get {
                return ResourceManager.GetString("LoginWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Google.
        /// </summary>
        public static string LoginWithGoogle {
            get {
                return ResourceManager.GetString("LoginWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main photo.
        /// </summary>
        public static string MainPhoto {
            get {
                return ResourceManager.GetString("MainPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in to do this.
        /// </summary>
        public static string MustBeLogged {
            get {
                return ResourceManager.GetString("MustBeLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My comments.
        /// </summary>
        public static string MyComments {
            get {
                return ResourceManager.GetString("MyComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nick.
        /// </summary>
        public static string Nick {
            get {
                return ResourceManager.GetString("Nick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No added image.
        /// </summary>
        public static string NoAddedImage {
            get {
                return ResourceManager.GetString("NoAddedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user with the email address in the system. Check the address and try again.
        /// </summary>
        public static string NoUserEmail {
            get {
                return ResourceManager.GetString("NoUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or in traditinal way.
        /// </summary>
        public static string OrTraditional {
            get {
                return ResourceManager.GetString("OrTraditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password was successfully changed!.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset.
        /// </summary>
        public static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords doesn&apos;t match.
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properly added article.
        /// </summary>
        public static string ProperlyAddedArticle {
            get {
                return ResourceManager.GetString("ProperlyAddedArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properly added bookmark.
        /// </summary>
        public static string ProperlyAddedBookmark {
            get {
                return ResourceManager.GetString("ProperlyAddedBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properly added category.
        /// </summary>
        public static string ProperlyAddedCategory {
            get {
                return ResourceManager.GetString("ProperlyAddedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properly added configuration key.
        /// </summary>
        public static string ProperlyAddedConfig {
            get {
                return ResourceManager.GetString("ProperlyAddedConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properly added image.
        /// </summary>
        public static string ProperlyAddedImage {
            get {
                return ResourceManager.GetString("ProperlyAddedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properly added tag.
        /// </summary>
        public static string ProperlyAddedTag {
            get {
                return ResourceManager.GetString("ProperlyAddedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password was changed properly.
        /// </summary>
        public static string ProperlyChangedPassword {
            get {
                return ResourceManager.GetString("ProperlyChangedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properly edited category.
        /// </summary>
        public static string ProperlyEditedCategory {
            get {
                return ResourceManager.GetString("ProperlyEditedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properly edited configuration key.
        /// </summary>
        public static string ProperlyEditedConfig {
            get {
                return ResourceManager.GetString("ProperlyEditedConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properly logged in.
        /// </summary>
        public static string ProperlyLogged {
            get {
                return ResourceManager.GetString("ProperlyLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properly logged out.
        /// </summary>
        public static string ProperlyLoggedOut {
            get {
                return ResourceManager.GetString("ProperlyLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properly removed article.
        /// </summary>
        public static string ProperlyRemovedArticle {
            get {
                return ResourceManager.GetString("ProperlyRemovedArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properly removed category.
        /// </summary>
        public static string ProperlyRemovedCategory {
            get {
                return ResourceManager.GetString("ProperlyRemovedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properly removed comment.
        /// </summary>
        public static string ProperlyRemovedComment {
            get {
                return ResourceManager.GetString("ProperlyRemovedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properly removed tag.
        /// </summary>
        public static string ProperlyRemovedTag {
            get {
                return ResourceManager.GetString("ProperlyRemovedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommend.
        /// </summary>
        public static string Recommend {
            get {
                return ResourceManager.GetString("Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best ragards!.
        /// </summary>
        public static string Regards {
            get {
                return ResourceManager.GetString("Regards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Try registering again and click on the link in a new message sent to the emai.
        /// </summary>
        public static string RegisterError {
            get {
                return ResourceManager.GetString("RegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulations.
        /// </summary>
        public static string Regulations {
            get {
                return ResourceManager.GetString("Regulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat new password.
        /// </summary>
        public static string RepeatNewPassword {
            get {
                return ResourceManager.GetString("RepeatNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat password.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting password on the site {0}.
        /// </summary>
        public static string ResettingPassword {
            get {
                return ResourceManager.GetString("ResettingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results:.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See similar articles.
        /// </summary>
        public static string SeeSimilarArticles {
            get {
                return ResourceManager.GetString("SeeSimilarArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing image.
        /// </summary>
        public static string SelectAnExistingImage {
            get {
                return ResourceManager.GetString("SelectAnExistingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected category ID&apos;s.
        /// </summary>
        public static string SelectedCategoryIDs {
            get {
                return ResourceManager.GetString("SelectedCategoryIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected tag ID&apos;s.
        /// </summary>
        public static string SelectedTagIDs {
            get {
                return ResourceManager.GetString("SelectedTagIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To the address were sent a message confirming the desire to open an account. Click on the link in order to complete the registration..
        /// </summary>
        public static string SentLink {
            get {
                return ResourceManager.GetString("SentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To the address were sent a message with further information. Click on the link in order to complete the reset..
        /// </summary>
        public static string SentLinkFurther {
            get {
                return ResourceManager.GetString("SentLinkFurther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with sending a message. Please try again.
        /// </summary>
        public static string SentLinkProblem {
            get {
                return ResourceManager.GetString("SentLinkProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        public static string ShowPassword {
            get {
                return ResourceManager.GetString("ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LuzzedroCMS.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags - add.
        /// </summary>
        public static string TagsAdd {
            get {
                return ResourceManager.GetString("TagsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team {0}.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regulations.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering on the site {0}!.
        /// </summary>
        public static string ThanksForRegistering {
            get {
                return ResourceManager.GetString("ThanksForRegistering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a comment you must be logged in.
        /// </summary>
        public static string ToAddCommentLogIn {
            get {
                return ResourceManager.GetString("ToAddCommentLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To reset password, click.
        /// </summary>
        public static string ToResetPassword {
            get {
                return ResourceManager.GetString("ToResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a file to start cropping.
        /// </summary>
        public static string UploadFileToStartCropping {
            get {
                return ResourceManager.GetString("UploadFileToStartCropping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with the email address already exists in the database. Check you have entered the address, or use the password recall.
        /// </summary>
        public static string UserEmailExists {
            get {
                return ResourceManager.GetString("UserEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with the nickname already exists in the database. Select a different nickname.
        /// </summary>
        public static string UserNickExists {
            get {
                return ResourceManager.GetString("UserNickExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User photo.
        /// </summary>
        public static string UserPhoto {
            get {
                return ResourceManager.GetString("UserPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been properly edited.
        /// </summary>
        public static string UserProperlyEdited {
            get {
                return ResourceManager.GetString("UserProperlyEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been properly removed.
        /// </summary>
        public static string UserProperlyRemoved {
            get {
                return ResourceManager.GetString("UserProperlyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users list.
        /// </summary>
        public static string UsersList {
            get {
                return ResourceManager.GetString("UsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        public static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t worry, we won&apos;t give anyone your e-mail, it is used to log on.
        /// </summary>
        public static string WontGivePassword {
            get {
                return ResourceManager.GetString("WontGivePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wykop.
        /// </summary>
        public static string Wykop {
            get {
                return ResourceManager.GetString("Wykop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add comment you must create a nick. Invent the name, which will by displayed near your comments.
        /// </summary>
        public static string YouMustCreateNick {
            get {
                return ResourceManager.GetString("YouMustCreateNick", resourceCulture);
            }
        }
    }
}
